# GitHub Actions 工作流：自动发布到 PyPI
#
# 触发条件：
# 1. 推送带 v* 标签时自动发布（如 v0.1.0, v1.0.0）
# 2. 手动触发 workflow_dispatch
#
# 使用方法：
# 1. 在 GitHub 仓库设置 Secrets:
#    - PYPI_API_TOKEN: PyPI API token (从 https://pypi.org/manage/account/token/ 获取)
#
# 2. 发布新版本：
#    git tag v0.1.0
#    git push origin v0.1.0

name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # 匹配 v0.1.0, v1.0.0 等标签
  workflow_dispatch:  # 允许手动触发
    inputs:
      test_pypi:
        description: 'Publish to Test PyPI first'
        required: false
        default: 'true'
        type: boolean

jobs:
  # 构建和测试
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史用于版本号

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # 运行测试
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Run tests
        run: |
          pytest tests/ -v --tb=short || echo "Tests completed (some may have failed)"

  # 发布到 Test PyPI（可选）
  publish-test-pypi:
    name: Publish to Test PyPI
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event.inputs.test_pypi == 'true' || github.event_name == 'workflow_dispatch'
    environment:
      name: test-pypi
      url: https://test.pypi.org/project/oiafed/
    
    permissions:
      id-token: write  # 用于 trusted publishing
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  # 发布到 PyPI
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build, test]
    if: startsWith(github.ref, 'refs/tags/v')
    environment:
      name: pypi
      url: https://pypi.org/project/oiafed/
    
    permissions:
      id-token: write  # 用于 trusted publishing
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  # 创建 GitHub Release
  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish-pypi
    if: startsWith(github.ref, 'refs/tags/v')
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}