artifact_uri: /home/nlp/ct/projects/OiaFed/${MLFLOW_TRACKING_URI:http:/172.19.138.200:5000}/116451831936848066/39246e318c4a494fb57b4da060a512dd/artifacts
end_time: null
entry_point_name: ''
experiment_id: '116451831936848066'
lifecycle_stage: active
run_id: 39246e318c4a494fb57b4da060a512dd
run_name: nosy-swan-842
source_name: ''
source_type: 4
source_version: ''
start_time: 1767005622228
status: 1
tags: []
user_id: ${MLFLOW_TRACKING_USERNAME:dongshou}
